#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 12 17:56:43 2021

@author: tnye
"""

###############################################################################
# Script that changes the rupture onset times of the .rupt files generated by
# FakeQuakes by changing the shallow shear wave fraction. It also stores the
# original .rupt files in another folder. This script is used when varying
# rupture velocity and should be run after generating the ruptures and before
# calculating the Green's functions. 
###############################################################################

# Imports
import numpy as np
from os import makedirs, path, rename
from distutils.dir_util import copy_tree
from glob import glob
from obspy.taup import TauPyModel
from mudpy import fakequakes

# Parameters
home = '/Users/tnye/FakeQuakes/parameters/vrupt/test/'
project_name = 'disp'
rupt_dir = f'{home}disp/output/ruptures'
orig_rupt_dir = f'{home}/disp/output/orig_ruptures'

shear_wave_fraction_shallow = 0.4

# Rename original ruptures folder 
if not path.exists(orig_rupt_dir):
    # Rename original ruptures folder 
    rename(rupt_dir, orig_rupt_dir)

# Create new folder called 'ruptures' to store new rise time .rupt files in
if not path.exists(rupt_dir):
    makedirs(rupt_dir)

# Copy over .log files
copy_tree(orig_rupt_dir, rupt_dir)

# Gather original rupture files
rupt_files = np.array(sorted(glob(f'{orig_rupt_dir}/*.rupt')))

# Loop through rupture files and change subfault onset time
for r in rupt_files:
    
    fault_array = np.genfromtxt(r)
    slip = np.sqrt(fault_array[:,8]**2 + fault_array[:,9]**2)
    mu = fault_array[:,13]
    model_name = 'mentawai.mod'
    hypocenter = [100.14, -3.49, 11.82]
    rise_time_depths = [10,15]
    M0 = sum(slip*fault_array[:,10]*fault_array[:,11]*mu)
    velmod = TauPyModel(model=home+project_name+'/structure/'+model_name.split('.')[0])

    f = open(r, 'r')
    header = f.readline().rstrip('\n')

    # Create empty array to store new onset times in
    # new_onset = np.array([])

    new_onset = fakequakes.get_rupture_onset(home,project_name,slip,fault_array,
                model_name,hypocenter,rise_time_depths, M0,velmod,sigma_rise_time=0.2,
                shear_wave_fraction_shallow=shear_wave_fraction_shallow)

    # Change rupt_time column to be new rupture onset times
    fault_array[:,12] = new_onset

    # Save new .rupt file
    rupt_name = r.split('/')[-1]
    np.savetxt(f'{rupt_dir}/{rupt_name}', fault_array, delimiter='\t',
               header=header, comments='', fmt='%s')
